spring:
    datasource:
        url: jdbc:mysql://192.168.99.100:3306/social?useSSL=false&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: secret

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    security:
        oauth2:
            client:
              registration:
                facebook:
                  clientId: 1572417336226710
                  clientSecret: 90d021459b495800c9b1447a270fa9dc
#                  accessTokenUri: https://graph.facebook.com/oauth/access_token
#                  redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
                  scope:
                    - user_posts
#                    - email
#                    - public_profile
#			      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#			      tokenName: oauth_token
#			      authenticationScheme: query
#			      clientAuthenticationScheme: form
#            resource:
#                userInfoUri: https://graph.facebook.com/me